# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: krzysiu.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rkrzysiu.proto\"S\n\nVitalSigns\x12\x0e\n\x06\x65nergy\x18\x01 \x01(\x05\x12\x12\n\nheart_rate\x18\x02 \x01(\x05\x12\x13\n\x0btemperature\x18\x03 \x01(\x02\x12\x0c\n\x04mood\x18\x04 \x01(\tb\x06proto3')



_VITALSIGNS = DESCRIPTOR.message_types_by_name['VitalSigns']
VitalSigns = _reflection.GeneratedProtocolMessageType('VitalSigns', (_message.Message,), {
  'DESCRIPTOR' : _VITALSIGNS,
  '__module__' : 'krzysiu_pb2'
  # @@protoc_insertion_point(class_scope:VitalSigns)
  })
_sym_db.RegisterMessage(VitalSigns)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VITALSIGNS._serialized_start=17
  _VITALSIGNS._serialized_end=100
# @@protoc_insertion_point(module_scope)
